export interface MetodoAnticonceptivo {
  id: string;
  nombre: string;
  tipo: 'Hormonal' | 'Barrera' | 'DIU' | 'Natural' | 'Emergencia' | 'Permanente';
  descripcion: string;
  efectividad: string;
  efectividadPerfecto?: string;
  efectividadTipico?: string;
  mecanismo: string;
  ventajas: string[];
  desventajas: string[];
  contraindicaciones?: string[];
  criteriosOMS?: string;
  duracion?: string;
  indicaciones?: string[];
  criterios: string;
}

export const METODOS_ANTICONCEPTIVOS: MetodoAnticonceptivo[] = [
  // ===== MÉTODOS HORMONALES =====
  {
    id: 'anticonceptivos-orales-combinados',
    nombre: 'Anticonceptivos Orales Combinados (ACO)',
    tipo: 'Hormonal',
    descripcion: 'Píldoras que contienen estrógeno (etinilestradiol) y progestina. Se toman diariamente durante 21-24 días seguidos de 4-7 días de descanso o placebo.',
    efectividadPerfecto: '99.7%',
    efectividadTipico: '91%',
    efectividad: '99.7% con uso perfecto, 91% con uso típico',
    duracion: 'Uso diario continuo',
    mecanismo: 'Inhiben la ovulación mediante supresión de FSH y LH, espesan el moco cervical dificultando el paso de espermatozoides y alteran el endometrio reduciendo la probabilidad de implantación.',
    ventajas: [
      'Alta efectividad anticonceptiva',
      'Regulan el ciclo menstrual y disminuyen la dismenorrea',
      'Reducen el sangrado menstrual hasta en 50%',
      'Disminuyen el acné y el hirsutismo',
      'Reducen el riesgo de cáncer de ovario y endometrio en 50%',
      'Disminuyen el riesgo de quistes ováricos funcionales',
      'Mejoran síntomas de síndrome premenstrual',
      'Tratamiento de endometriosis',
    ],
    desventajas: [
      'Requieren toma diaria a la misma hora',
      'No protegen contra ITS/VIH',
      'Efectos secundarios: náuseas, cefalea, mastalgia, cambios de ánimo',
      'Sangrado intermenstrual en los primeros meses',
      'Aumento del riesgo de tromboembolismo venoso',
      'Contraindicados en mujeres fumadoras >35 años',
      'Interacciones medicamentosas (anticonvulsivantes, rifampicina)',
    ],
    contraindicaciones: [
      'Embarazo',
      'Lactancia materna <6 semanas postparto',
      'Fumadoras >35 años',
      'Hipertensión arterial severa o con enfermedad vascular',
      'Tromboembolismo venoso actual o historia',
      'Cardiopatía isquémica o accidente cerebrovascular',
      'Migraña con aura a cualquier edad',
      'Diabetes con nefropatía, retinopatía o neuropatía',
      'Cáncer de mama actual',
      'Cirrosis hepática descompensada o tumores hepáticos',
      'Lupus eritematoso sistémico con anticuerpos antifosfolípidos positivos',
    ],
    criteriosOMS: 'Categoría 1-2 para mayoría de mujeres sanas. Categoría 3-4 para condiciones especificadas.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'pildora-progestina-sola',
    nombre: 'Píldora de Solo Progestina (Minipíldora)',
    tipo: 'Hormonal',
    descripcion: 'Píldora que contiene solo progestágeno sin estrógeno. Se toma diariamente sin descanso, a la misma hora todos los días.',
    efectividadPerfecto: '99.7%',
    efectividadTipico: '91%',
    efectividad: '99.7% con uso perfecto, 91% con uso típico',
    duracion: 'Uso diario continuo sin pausa',
    mecanismo: 'Espesa el moco cervical, suprime la ovulación en aproximadamente 50% de los ciclos, y altera el endometrio.',
    ventajas: [
      'Puede usarse durante lactancia materna',
      'No contiene estrógeno (menor riesgo cardiovascular)',
      'Adecuada para mujeres con contraindicación a estrógenos',
      'Puede usarse en fumadoras de cualquier edad',
      'Disminuye cólicos menstruales',
      'Puede causar amenorrea (beneficioso en algunas mujeres)',
    ],
    desventajas: [
      'Debe tomarse a la misma hora todos los días (ventana de 3 horas)',
      'Sangrado irregular muy común',
      'No protege contra ITS',
      'Menor efectividad con olvidos',
      'Puede causar quistes ováricos funcionales',
      'Puede aumentar cefaleas',
    ],
    contraindicaciones: [
      'Embarazo',
      'Cáncer de mama actual',
      'Sangrado vaginal sin diagnóstico',
      'Cirrosis severa o tumor hepático',
    ],
    criteriosOMS: 'Categoría 1-2 para mayoría de condiciones. Excelente opción en lactancia.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'inyectable-mensual',
    nombre: 'Anticonceptivo Inyectable Mensual',
    tipo: 'Hormonal',
    descripcion: 'Inyección intramuscular que contiene estrógeno y progestina. Se aplica una vez al mes.',
    efectividadPerfecto: '99.9%',
    efectividadTipico: '94%',
    efectividad: '99.9% con uso perfecto, 94% con uso típico',
    duracion: 'Inyección cada 30 días (±3 días)',
    mecanismo: 'Inhibe la ovulación, espesa el moco cervical y altera el endometrio.',
    ventajas: [
      'Alta efectividad',
      'No requiere acción diaria',
      'Administración mensual conveniente',
      'Regula el ciclo menstrual',
      'Menos olvidos que la píldora',
      'Reversible',
    ],
    desventajas: [
      'Requiere visita mensual para aplicación',
      'No protege contra ITS',
      'Efectos secundarios similares a ACO',
      'Aumento de peso en algunas usuarias',
      'Sangrado irregular inicial',
      'Mismas contraindicaciones que ACO combinados',
    ],
    contraindicaciones: [
      'Similares a anticonceptivos orales combinados',
      'Embarazo',
      'Fumadoras >35 años',
      'Enfermedad tromboembólica',
      'Cáncer de mama',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'inyectable-trimestral',
    nombre: 'Acetato de Medroxiprogesterona (DMPA) - Inyectable Trimestral',
    tipo: 'Hormonal',
    descripcion: 'Inyección intramuscular o subcutánea de progestágeno solo (150mg medroxiprogesterona). Se aplica cada 3 meses.',
    efectividadPerfecto: '99.8%',
    efectividadTipico: '94%',
    efectividad: '99.8% con uso perfecto, 94% con uso típico',
    duracion: 'Inyección cada 12 semanas (±2 semanas)',
    mecanismo: 'Inhibe la ovulación de manera constante, espesa el moco cervical y produce atrofia endometrial.',
    ventajas: [
      'Altamente efectivo y de larga duración',
      'Solo 4 inyecciones al año',
      'No contiene estrógeno',
      'Puede usarse durante lactancia',
      'Amenorrea en 50% usuarias al año (beneficio)',
      'Disminuye riesgo de cáncer endometrial',
      'Útil en endometriosis y anemia',
      'Puede usarse en mujeres con epilepsia',
    ],
    desventajas: [
      'Sangrado irregular frecuente en primeros meses',
      'Aumento de peso (2-3 kg promedio al año)',
      'Retorno de fertilidad demorado (6-12 meses post-suspensión)',
      'Disminución de densidad mineral ósea (reversible)',
      'No protege contra ITS',
      'Puede aumentar depresión',
      'Cefaleas, mastalgia',
    ],
    contraindicaciones: [
      'Embarazo',
      'Cáncer de mama actual',
      'Sangrado vaginal sin diagnóstico',
      'Enfermedad cardiovascular severa',
      'Precaución en adolescentes (efecto óseo)',
    ],
    criteriosOMS: 'Categoría 2 en adolescentes por efecto en densidad ósea. Categoría 1-2 en otros grupos.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'implante-subdermico',
    nombre: 'Implante Subdérmico de Etonogestrel',
    tipo: 'Hormonal',
    descripcion: 'Varilla flexible de 4cm que contiene etonogestrel. Se inserta subdérmicamente en el brazo y libera progestágeno continuamente.',
    efectividadPerfecto: '99.95%',
    efectividadTipico: '99.95%',
    efectividad: 'Mayor a 99.9% - uno de los más efectivos',
    duracion: '3 años',
    mecanismo: 'Inhibe la ovulación de forma constante, espesa el moco cervical y produce atrofia endometrial.',
    ventajas: [
      'Máxima efectividad anticonceptiva (comparable a esterilización)',
      'Larga duración (3 años)',
      'No requiere acción diaria ni mensual',
      'Rápida reversibilidad (fertilidad retorna inmediatamente tras retiro)',
      'No contiene estrógeno',
      'Puede usarse durante lactancia',
      'Discreto (no visible)',
      'Reduce dismenorrea y síntomas de endometriosis',
    ],
    desventajas: [
      'Sangrado irregular muy frecuente (patrón impredecible)',
      'Requiere procedimiento para inserción y retiro',
      'Costo inicial más alto',
      'No protege contra ITS',
      'Puede causar cefalea, acné, mastalgia',
      'Aumento de peso en algunas usuarias',
      'Posible alteración del humor',
    ],
    contraindicaciones: [
      'Embarazo',
      'Cáncer de mama actual o historia reciente',
      'Sangrado vaginal sin diagnóstico',
      'Enfermedad hepática severa o tumor hepático',
      'Hipersensibilidad al etonogestrel',
    ],
    criteriosOMS: 'Categoría 1 para mayoría de mujeres. Excelente opción de primera línea.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'anillo-vaginal',
    nombre: 'Anillo Vaginal Anticonceptivo',
    tipo: 'Hormonal',
    descripcion: 'Anillo flexible de plástico que se inserta en la vagina y libera estrógeno y progestina. Se usa 3 semanas continuas, 1 semana de descanso.',
    efectividadPerfecto: '99.7%',
    efectividadTipico: '91%',
    efectividad: '99.7% con uso perfecto, 91% con uso típico',
    duracion: 'Cambio mensual (3 semanas con anillo, 1 sin)',
    mecanismo: 'Inhibe la ovulación, espesa el moco cervical y altera el endometrio mediante liberación constante de hormonas.',
    ventajas: [
      'Uso mensual (mayor comodidad que píldora diaria)',
      'Absorción vaginal evita primer paso hepático',
      'Dosis hormonal más baja que píldoras',
      'Efectividad no afectada por vómitos o diarrea',
      'Regula ciclo menstrual',
      'La usuaria puede insertarlo y retirarlo',
    ],
    desventajas: [
      'Puede ser expulsado espontáneamente',
      'Requiere manipulación vaginal',
      'Puede causar leucorrea o irritación vaginal',
      'Visible para la pareja durante relaciones sexuales',
      'No protege contra ITS',
      'Mismas contraindicaciones que ACO combinados',
      'Costo elevado',
    ],
    contraindicaciones: [
      'Similares a anticonceptivos orales combinados',
      'Prolapso uterino severo',
      'Estenosis vaginal',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'parche-anticonceptivo',
    nombre: 'Parche Transdérmico Anticonceptivo',
    tipo: 'Hormonal',
    descripcion: 'Parche adhesivo que se coloca en la piel (abdomen, glúteos, espalda o brazo) y libera estrógeno y progestina. Se cambia semanalmente durante 3 semanas, 1 semana sin parche.',
    efectividadPerfecto: '99.7%',
    efectividadTipico: '91%',
    efectividad: '99.7% con uso perfecto, 91% con uso típico',
    duracion: 'Cambio semanal (3 semanas con parche, 1 sin)',
    mecanismo: 'Inhibe la ovulación, espesa el moco cervical y altera el endometrio mediante liberación transdérmica de hormonas.',
    ventajas: [
      'Cambio semanal más conveniente que píldora diaria',
      'Efectividad no afectada por vómitos o diarrea',
      'Regula el ciclo menstrual',
      'Similar eficacia a ACO',
      'Fácil de usar',
    ],
    desventajas: [
      'Visible en la piel',
      'Puede causar irritación cutánea o dermatitis de contacto',
      'Puede despegarse (especialmente con calor, sudor, humedad)',
      'No recomendado en mujeres >90 kg (menor efectividad)',
      'Mayor exposición a estrógenos que ACO',
      'No protege contra ITS',
      'Mismas contraindicaciones que ACO combinados',
    ],
    contraindicaciones: [
      'Similares a anticonceptivos orales combinados',
      'Obesidad severa (IMC >30 kg/m²)',
      'Enfermedades dermatológicas en sitio de aplicación',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },

  // ===== DISPOSITIVOS INTRAUTERINOS (DIU) =====
  {
    id: 'diu-cobre',
    nombre: 'DIU de Cobre (T de Cobre 380A)',
    tipo: 'DIU',
    descripcion: 'Dispositivo intrauterino en forma de T cubierto de cobre. Se inserta en la cavidad uterina por personal capacitado. Método de larga duración sin hormonas.',
    efectividadPerfecto: '99.4%',
    efectividadTipico: '99.2%',
    efectividad: 'Mayor a 99% - uno de los más efectivos',
    duracion: '10-12 años',
    mecanismo: 'El cobre tiene efecto espermicida, interfiere con la capacitación espermática, la fertilización y previene la implantación mediante reacción inflamatoria endometrial.',
    ventajas: [
      'Altamente efectivo y de muy larga duración',
      'No contiene hormonas (no afecta lactancia ni peso)',
      'Inmediatamente reversible tras retiro',
      'No requiere acción diaria',
      'Costo-efectivo a largo plazo',
      'Puede usarse como anticoncepción de emergencia (hasta 5 días post-coito)',
      'No interfiere con relaciones sexuales',
      'Puede usarse en cualquier edad',
    ],
    desventajas: [
      'Aumenta sangrado menstrual y cólicos (30-50% usuarias)',
      'Sangrado puede prolongarse 1-2 días',
      'Requiere inserción por personal entrenado',
      'Riesgo de expulsión (5-10% en primer año)',
      'Riesgo bajo de perforación uterina (1-2/1000)',
      'No protege contra ITS',
      'Requiere controles periódicos',
      'Posible anemia por hipermenorrea',
    ],
    contraindicaciones: [
      'Embarazo o sospecha de embarazo',
      'Infección pélvica activa o reciente (<3 meses)',
      'ITS activa',
      'Malformaciones uterinas severas',
      'Cáncer cervical o endometrial',
      'Sangrado vaginal sin diagnóstico',
      'Enfermedad de Wilson',
      'Alergia al cobre',
    ],
    indicaciones: [
      'Mujeres que desean anticoncepción de larga duración',
      'Mujeres con contraindicación a hormonas',
      'Lactancia materna',
      'Nuligestas y multíparas',
      'Mujeres con hipermenorrea NO (contraindicado)',
    ],
    criteriosOMS: 'Categoría 1 para mayoría de mujeres. Primera opción de larga duración.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'diu-levonorgestrel',
    nombre: 'DIU con Levonorgestrel (SIU-LNG)',
    tipo: 'DIU',
    descripcion: 'Dispositivo intrauterino en forma de T que libera levonorgestrel (progestágeno) continuamente. Disponible en dosis de 52mg (5 años) y 19.5mg (3 años).',
    efectividadPerfecto: '99.8%',
    efectividadTipico: '99.8%',
    efectividad: 'Mayor a 99.8% - máxima efectividad',
    duracion: '3-5 años según dosis',
    mecanismo: 'Efecto local de levonorgestrel produce atrofia endometrial, espesa el moco cervical e inhibe parcialmente la ovulación.',
    ventajas: [
      'Máxima efectividad anticonceptiva',
      'Reduce sangrado menstrual hasta 90%',
      'Amenorrea en 20-30% usuarias al año',
      'Tratamiento de menorragia y dismenorrea',
      'Útil en endometriosis y adenomiosis',
      'Efecto hormonal principalmente local',
      'No requiere acción diaria',
      'Reversible inmediatamente',
      'Puede prevenir hiperplasia endometrial en TRH',
    ],
    desventajas: [
      'Sangrado irregular frecuente primeros 3-6 meses',
      'Manchado intermenstrual',
      'Puede causar quistes ováricos funcionales (usualmente asintomáticos)',
      'Requiere inserción por personal capacitado',
      'Costo inicial elevado',
      'No protege contra ITS',
      'Posibles efectos sistémicos: acné, mastalgia, cefalea',
    ],
    contraindicaciones: [
      'Embarazo',
      'Infección pélvica activa o reciente',
      'Malformaciones uterinas severas',
      'Cáncer de mama actual o reciente',
      'Cáncer cervical o endometrial',
      'Sangrado vaginal sin diagnóstico',
      'Enfermedad hepática severa',
    ],
    indicaciones: [
      'Anticoncepción de larga duración',
      'Menorragia (primera línea de tratamiento)',
      'Dismenorrea severa',
      'Endometriosis',
      'Adenomiosis',
      'Protección endometrial en terapia de reemplazo hormonal',
    ],
    criteriosOMS: 'Categoría 1-2 para mayoría de condiciones. Excelente opción terapéutica.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },

  // ===== MÉTODOS DE BARRERA =====
  {
    id: 'condon-masculino',
    nombre: 'Condón Masculino (Preservativo)',
    tipo: 'Barrera',
    descripcion: 'Funda de látex, poliuretano o poliisopreno que se coloca sobre el pene erecto antes de la penetración. Único método que protege contra ITS.',
    efectividadPerfecto: '98%',
    efectividadTipico: '82%',
    efectividad: '98% con uso perfecto, 82% con uso típico',
    duracion: 'Uso único por relación sexual',
    mecanismo: 'Barrera física que impide el contacto entre espermatozoides y óvulo, y previene el contacto directo con fluidos corporales.',
    ventajas: [
      'Única protección efectiva contra ITS incluyendo VIH',
      'Ampliamente disponible y económico',
      'No requiere prescripción médica',
      'Sin efectos secundarios sistémicos',
      'Participación masculina en anticoncepción',
      'Puede prolongar la eyaculación',
      'Disponible en farmacias, supermercados',
      'Puede usarse como respaldo de otros métodos',
    ],
    desventajas: [
      'Requiere uso correcto en cada relación sexual',
      'Puede romperse o deslizarse (2-5% de usos)',
      'Requiere colocación en erección',
      'Puede disminuir sensibilidad',
      'Interrupción del acto sexual',
      'Alergia al látex (usar alternativas)',
      'Requiere retiro inmediato post-eyaculación',
      'Almacenamiento adecuado necesario',
    ],
    contraindicaciones: [
      'Alergia al látex (usar poliuretano)',
      'Disfunción eréctil severa',
    ],
    indicaciones: [
      'Protección contra ITS (indicación primaria)',
      'Anticoncepción ocasional',
      'Complemento de otros métodos',
      'Parejas con múltiples compañeros sexuales',
      'Prevención de transmisión VIH',
    ],
    criteriosOMS: 'Categoría 1 - sin restricciones. Recomendado para todos.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'condon-femenino',
    nombre: 'Condón Femenino (Preservativo Femenino)',
    tipo: 'Barrera',
    descripcion: 'Funda de poliuretano o nitrilo con dos anillos que se inserta en la vagina antes de la relación sexual. Protege contra embarazo e ITS.',
    efectividadPerfecto: '95%',
    efectividadTipico: '79%',
    efectividad: '95% con uso perfecto, 79% con uso típico',
    duracion: 'Uso único por relación sexual',
    mecanismo: 'Barrera física que impide el contacto entre espermatozoides y óvulo, y previene contacto con fluidos corporales e ITS.',
    ventajas: [
      'Protege contra ITS incluyendo VIH',
      'Bajo control de la mujer',
      'Puede insertarse hasta 8 horas antes',
      'No interrumpe el acto sexual',
      'No requiere retiro inmediato post-coito',
      'Alternativa a alergia al látex',
      'Puede usarse con lubricantes base aceite',
      'Cubre más área que condón masculino',
    ],
    desventajas: [
      'Menos disponible y más costoso que condón masculino',
      'Requiere práctica para uso correcto',
      'Puede ser visible externamente',
      'Puede producir ruido durante relación',
      'Menor efectividad que condón masculino',
      'Puede deslizarse dentro de la vagina',
      'Requiere educación en uso correcto',
    ],
    contraindicaciones: [
      'Ninguna absoluta',
      'Prolapso vaginal severo (relativa)',
    ],
    indicaciones: [
      'Protección contra ITS',
      'Mujeres que desean control del método de barrera',
      'Alergia al látex de condón masculino',
      'Parejas que no pueden usar condón masculino',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'diafragma',
    nombre: 'Diafragma con Espermicida',
    tipo: 'Barrera',
    descripcion: 'Copa de silicona flexible que se coloca en la vagina cubriendo el cuello uterino antes de la relación sexual. Debe usarse con espermicida.',
    efectividadPerfecto: '94%',
    efectividadTipico: '88%',
    efectividad: '94% con uso perfecto, 88% con uso típico',
    duracion: 'Reutilizable hasta 2 años con cuidado adecuado',
    mecanismo: 'Barrera mecánica que cubre el cérvix impidiendo entrada de espermatozoides. El espermicida inactiva espermatozoides.',
    ventajas: [
      'Reutilizable (económico a largo plazo)',
      'Puede insertarse hasta 6 horas antes',
      'Sin efectos hormonales sistémicos',
      'Bajo control de la mujer',
      'Puede usarse durante menstruación',
    ],
    desventajas: [
      'Requiere prescripción y ajuste profesional',
      'Mayor riesgo de infección urinaria',
      'Requiere manipulación vaginal',
      'Debe permanecer 6-8 horas post-coito',
      'Reajuste necesario tras parto o cambio de peso >5kg',
      'No protege efectivamente contra ITS',
      'Puede desplazarse durante relación',
      'Menor efectividad en multíparas',
    ],
    contraindicaciones: [
      'Alergia al látex o espermicida',
      'Infección urinaria recurrente',
      'Historia de síndrome de shock tóxico',
      'Anomalías anatómicas vaginales',
      'Prolapso uterino',
      'Primer mes post-parto',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },

  // ===== MÉTODOS NATURALES =====
  {
    id: 'lactancia-amenorrea',
    nombre: 'Método de Lactancia y Amenorrea (MELA)',
    tipo: 'Natural',
    descripcion: 'Método anticonceptivo natural basado en lactancia materna exclusiva. Efectivo solo si se cumplen 3 condiciones estrictas.',
    efectividadPerfecto: '98%',
    efectividadTipico: '98%',
    efectividad: '98% si se cumplen todos los criterios',
    duracion: 'Hasta 6 meses postparto',
    mecanismo: 'La succión frecuente del pezón suprime la liberación de GnRH, FSH y LH, inhibiendo la ovulación.',
    ventajas: [
      'Sin costo',
      'Sin efectos secundarios',
      'Promueve beneficios de lactancia materna',
      'Inmediatamente reversible',
      'Uso temporal mientras se decide otro método',
    ],
    desventajas: [
      'Requiere lactancia exclusiva cada 4 horas día y 6 horas noche',
      'Solo efectivo hasta 6 meses postparto',
      'No protege contra ITS',
      'Requiere amenorrea completa',
      'Difícil de mantener en vida moderna',
      'No adecuado para mujeres que trabajan fuera',
    ],
    contraindicaciones: [
      'VIH positivo (contraindicada lactancia)',
      'Uso de medicamentos incompatibles con lactancia',
      'Condiciones que impidan lactancia exclusiva',
    ],
    indicaciones: [
      'Mujeres en lactancia exclusiva que cumplen todos los criterios',
      'Transición temporal a otro método',
    ],
    criteriosOMS: 'Categoría 1 si se cumplen 3 criterios: amenorrea, <6 meses postparto, lactancia exclusiva',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'metodo-ritmo',
    nombre: 'Método del Ritmo o Calendario',
    tipo: 'Natural',
    descripcion: 'Método basado en cálculo de días fértiles según duración de ciclos menstruales previos. Se evitan relaciones o se usa barrera en días fértiles.',
    efectividadPerfecto: '91%',
    efectividadTipico: '76%',
    efectividad: '91% con uso perfecto, 76% con uso típico',
    duracion: 'Continuo',
    mecanismo: 'Evitar relaciones sexuales durante el período fértil (aproximadamente días 10-17 del ciclo).',
    ventajas: [
      'Sin costo',
      'Sin efectos secundarios',
      'Aceptable para grupos con objeciones religiosas',
      'Aumenta conocimiento del ciclo menstrual',
      'Puede usarse para planificar embarazo',
    ],
    desventajas: [
      'Baja efectividad comparada con métodos modernos',
      'Requiere ciclos regulares',
      'Abstinencia o uso de barrera durante días fértiles',
      'No adecuado en ciclos irregulares',
      'No protege contra ITS',
      'Requiere registro diario',
      'Dificulta espontaneidad sexual',
    ],
    contraindicaciones: [
      'Ciclos menstruales irregulares',
      'Postparto reciente',
      'Perimenopausia',
      'Post-aborto',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'temperatura-basal',
    nombre: 'Método de Temperatura Basal Corporal',
    tipo: 'Natural',
    descripcion: 'Medición diaria de temperatura basal (al despertar) para identificar ovulación. Relaciones permitidas solo en fase postovulatoria.',
    efectividadPerfecto: '99%',
    efectividadTipico: '75%',
    efectividad: '99% con uso perfecto, 75% con uso típico',
    duracion: 'Continuo',
    mecanismo: 'La progesterona post-ovulatoria aumenta temperatura 0.2-0.5°C. Días seguros son 3 días después del alza térmica hasta menstruación.',
    ventajas: [
      'Bajo costo',
      'Sin efectos secundarios',
      'Ayuda a conocer ciclo y fertilidad',
      'Útil para planificación de embarazo',
    ],
    desventajas: [
      'Requiere medición diaria estricta',
      'Solo identifica ovulación después de ocurrida',
      'Afectada por enfermedad, estrés, alcohol',
      'Requiere abstinencia prolongada',
      'No protege contra ITS',
      'Baja efectividad con uso típico',
      'Requiere entrenamiento y compromiso',
    ],
    contraindicaciones: [
      'Ciclos irregulares',
      'Trabajo nocturno o sueño irregular',
      'Enfermedades febriles frecuentes',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'moco-cervical',
    nombre: 'Método de Billings (Moco Cervical)',
    tipo: 'Natural',
    descripcion: 'Identificación de fertilidad mediante observación diaria de características del moco cervical. Moco transparente y elástico indica fertilidad.',
    efectividadPerfecto: '97%',
    efectividadTipico: '77%',
    efectividad: '97% con uso perfecto, 77% con uso típico',
    duracion: 'Continuo',
    mecanismo: 'El moco cervical cambia con hormonas: escaso y espeso (infértil) a abundante y elástico tipo clara de huevo (fértil).',
    ventajas: [
      'Sin costo',
      'Sin efectos secundarios',
      'Aumenta autoconocimiento',
      'Identifica fertilidad en tiempo real',
      'Útil para lograr embarazo',
    ],
    desventajas: [
      'Requiere evaluación diaria',
      'Afectado por infecciones vaginales',
      'Requiere abstinencia durante fase fértil',
      'Curva de aprendizaje inicial',
      'No protege contra ITS',
      'Menor efectividad con uso típico',
    ],
    contraindicaciones: [
      'Infecciones vaginales recurrentes',
      'Uso de duchas vaginales',
      'Postparto o lactancia reciente',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'coito-interrumpido',
    nombre: 'Coito Interrumpido (Retiro)',
    tipo: 'Natural',
    descripcion: 'El hombre retira el pene de la vagina antes de la eyaculación. NO es un método recomendable.',
    efectividadPerfecto: '96%',
    efectividadTipico: '73%',
    efectividad: '96% con uso perfecto, 73% con uso típico - NO RECOMENDADO',
    duracion: 'Cada relación sexual',
    mecanismo: 'Evitar deposición de semen en vagina mediante retiro pre-eyaculatorio.',
    ventajas: [
      'Sin costo',
      'Disponible en cualquier momento',
      'Sin efectos secundarios',
      'Mejor que no usar nada',
    ],
    desventajas: [
      'Muy baja efectividad',
      'Requiere autocontrol extremo',
      'Espermatozoides presentes en líquido pre-eyaculatorio',
      'No protege contra ITS',
      'Disminuye placer sexual',
      'Alto riesgo de falla',
      'No recomendado por MINSAL',
    ],
    contraindicaciones: [
      'No recomendado como método anticonceptivo',
      'Inadecuado en adolescentes o parejas jóvenes',
      'Eyaculación precoz',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },

  // ===== ANTICONCEPCIÓN DE EMERGENCIA =====
  {
    id: 'pae-levonorgestrel',
    nombre: 'Píldora Anticonceptiva de Emergencia (PAE) - Levonorgestrel',
    tipo: 'Emergencia',
    descripcion: 'Píldora de 1.5mg de levonorgestrel que se toma lo antes posible después de relación sexual sin protección o falla de método. Disponible en farmacias sin receta.',
    efectividadPerfecto: '89% si se usa dentro de 72 horas',
    efectividadTipico: '75-89%',
    efectividad: '89% dentro de 24 horas, disminuye con el tiempo (75% a las 72 horas)',
    duracion: 'Uso único post-coital',
    mecanismo: 'Retrasa o inhibe la ovulación. NO interrumpe embarazo establecido. NO es abortivo.',
    ventajas: [
      'Disponible sin receta médica',
      'Previene embarazo después de relación sin protección',
      'Segura y bien tolerada',
      'No tiene contraindicaciones absolutas',
      'Puede usarse múltiples veces (no método regular)',
      'Efectiva si se usa tempranamente',
    ],
    desventajas: [
      'Menor efectividad que métodos regulares',
      'Debe usarse lo antes posible (<72 horas)',
      'No protege contra ITS',
      'Puede causar náuseas, sangrado irregular',
      'No protege relaciones posteriores del mismo ciclo',
      'Menos efectiva en mujeres con IMC >25',
      'No debe usarse como método regular',
    ],
    contraindicaciones: [
      'Embarazo confirmado (no por que cause daño, sino porque es inefectiva)',
      'Ninguna contraindicación médica absoluta',
    ],
    indicaciones: [
      'Relación sexual sin protección',
      'Falla de método de barrera (ruptura de condón)',
      'Olvido de píldoras anticonceptivas',
      'Expulsión de DIU',
      'Violación sexual',
      'Desplazamiento de diafragma',
    ],
    criteriosOMS: 'Categoría 1 - sin restricciones. Disponible para todas las mujeres.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'pae-ulipristal',
    nombre: 'PAE de Acetato de Ulipristal',
    tipo: 'Emergencia',
    descripcion: 'Píldora de 30mg de acetato de ulipristal. Más efectiva que levonorgestrel y eficaz hasta 120 horas post-coito.',
    efectividadPerfecto: '98% dentro de 120 horas',
    efectividadTipico: '98%',
    efectividad: '98% hasta 120 horas (5 días) post-coito',
    duracion: 'Uso único post-coital',
    mecanismo: 'Modulador selectivo del receptor de progesterona que retrasa o inhibe la ovulación. NO es abortivo.',
    ventajas: [
      'Mayor efectividad que levonorgestrel',
      'Efectiva hasta 120 horas (5 días)',
      'Efectividad no disminuye significativamente con el tiempo',
      'Más efectiva en mujeres con sobrepeso',
      'Una sola dosis',
    ],
    desventajas: [
      'Requiere receta médica',
      'Más costosa que levonorgestrel',
      'Menor disponibilidad',
      'No protege contra ITS',
      'Puede causar sangrado irregular',
      'No debe usarse como método regular',
    ],
    contraindicaciones: [
      'Embarazo confirmado',
      'Asma severa no controlada',
      'Hipersensibilidad al principio activo',
    ],
    indicaciones: [
      'Similares a PAE de levonorgestrel',
      'Preferible cuando han pasado >72 horas',
      'Mujeres con IMC >25 kg/m²',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'diu-emergencia',
    nombre: 'DIU de Cobre como Anticoncepción de Emergencia',
    tipo: 'Emergencia',
    descripcion: 'Inserción de DIU de cobre hasta 5 días después de relación sin protección. El método de emergencia más efectivo.',
    efectividadPerfecto: '>99.9%',
    efectividadTipico: '>99%',
    efectividad: 'Mayor a 99% - método más efectivo de anticoncepción de emergencia',
    duracion: 'Hasta 5 días post-coito, luego 10-12 años de protección',
    mecanismo: 'Interfiere con fertilización e implantación mediante efecto tóxico del cobre sobre espermatozoides y óvulo.',
    ventajas: [
      'Método más efectivo de anticoncepción de emergencia',
      'Proporciona anticoncepción continua por 10-12 años',
      'Puede insertarse hasta 5 días post-coito',
      'Efectivo independiente del peso',
      'No hormonal',
    ],
    desventajas: [
      'Requiere procedimiento de inserción',
      'Disponibilidad limitada de personal capacitado',
      'Contraindicado en infecciones pélvicas',
      'Mayor costo inicial',
      'No protege contra ITS',
    ],
    contraindicaciones: [
      'Embarazo existente',
      'Infección pélvica activa o reciente',
      'ITS activa',
      'Anomalías uterinas',
    ],
    indicaciones: [
      'Anticoncepción de emergencia con deseo de método de larga duración',
      'Mujeres con obesidad (más efectivo que PAE)',
      'Han pasado >72 horas de relación sin protección',
      'Violación sexual con seguimiento',
    ],
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },

  // ===== MÉTODOS PERMANENTES =====
  {
    id: 'ligadura-tubarica',
    nombre: 'Ligadura Tubárica (Esterilización Femenina)',
    tipo: 'Permanente',
    descripcion: 'Procedimiento quirúrgico que obstruye o secciona las trompas de Falopio. Método anticonceptivo permanente para mujeres.',
    efectividadPerfecto: '99.5%',
    efectividadTipico: '99.5%',
    efectividad: 'Mayor a 99.5% - método permanente',
    duracion: 'Permanente (reversión posible pero no garantizada)',
    mecanismo: 'Obstrucción mecánica de trompas que impide encuentro entre óvulo y espermatozoide.',
    ventajas: [
      'Método permanente altamente efectivo',
      'No interfiere con relaciones sexuales',
      'No requiere acción futura',
      'No altera hormonas ni menstruación',
      'No tiene efectos a largo plazo en salud',
      'Puede realizarse postparto o postcesárea',
      'Disminuye riesgo de cáncer de ovario',
    ],
    desventajas: [
      'Permanente - difícil de revertir',
      'Requiere cirugía (laparoscopia o minilaparotomía)',
      'Riesgos quirúrgicos y anestésicos',
      'Costosa',
      'No protege contra ITS',
      'Posible embarazo ectópico si falla',
      'Requiere consejería y consentimiento informado',
      'Período de reflexión obligatorio (30 días en Chile)',
    ],
    contraindicaciones: [
      'Falta de consejería adecuada o decisión bajo presión',
      'Incertidumbre sobre permanencia del método',
      'Condiciones médicas que aumenten riesgo quirúrgico',
      'Infección pélvica activa',
    ],
    indicaciones: [
      'Mujeres que han completado su paridad deseada',
      'Contraindicación severa a embarazo',
      'Decisión voluntaria, informada y consciente',
      'Edad >21 años en Chile (Ley 20.418)',
    ],
    criteriosOMS: 'Categoría 1 si decisión informada. Requiere consejería obligatoria.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
  {
    id: 'vasectomia',
    nombre: 'Vasectomía (Esterilización Masculina)',
    tipo: 'Permanente',
    descripcion: 'Procedimiento quirúrgico ambulatorio que secciona los conductos deferentes. Método anticonceptivo permanente para hombres.',
    efectividadPerfecto: '99.9%',
    efectividadTipico: '99.85%',
    efectividad: 'Mayor a 99.9% después de 3 meses - método más efectivo',
    duracion: 'Permanente (reversión posible pero no garantizada)',
    mecanismo: 'Obstrucción de conductos deferentes impide paso de espermatozoides a semen eyaculado.',
    ventajas: [
      'Método más efectivo de anticoncepción',
      'Procedimiento simple, ambulatorio, anestesia local',
      'Menor riesgo que ligadura tubárica',
      'Más económico que esterilización femenina',
      'No afecta función sexual ni libido',
      'Eyaculación normal (semen sin espermatozoides)',
      'Permanente sin mantenimiento',
    ],
    desventajas: [
      'Permanente - reversión difícil y no garantizada',
      'Requiere espermograma de control (efectiva después de 3 meses)',
      'Uso de otro método hasta confirmar azoospermia',
      'Riesgos menores: hematoma, infección, dolor',
      'No protege contra ITS',
      'Requiere consejería y consentimiento informado',
      'Arrepentimiento posible en hombres jóvenes',
    ],
    contraindicaciones: [
      'Falta de consejería o decisión bajo presión',
      'Incertidumbre sobre permanencia',
      'Infección escrotal activa',
      'Trastornos de coagulación no controlados',
      'Hernia inguinoescrotal grande',
    ],
    indicaciones: [
      'Hombres que han completado su paridad deseada',
      'Pareja con contraindicación a otros métodos',
      'Decisión voluntaria, informada y consciente',
      'Preferible a esterilización femenina por menor riesgo',
    ],
    criteriosOMS: 'Categoría 1 si decisión informada. Método recomendado para anticoncepción permanente.',
    criterios: 'https://www.minsal.cl/portal/url/item/78bf5e5433252d16e04001011f014555.pdf',
  },
];
